### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by abhiyerra** [abhiyerra/org-reading#3]
Have a reading.el mode which allows you to create and keep track of reading.
# Issues

There is still a lot I'd like to do with this script. Lots of
[Quantified Self](http://quantifiedself.com/) type stuff can be done. I want to get to that
point. Right now I have some humble code. Once enough of these
features have been fixed I will throw it on Github or send it off to
org-mode if they want to add it to contrib. Right now its my
personal hack which doesn't have a lot of design considerations in
mind.
## New Book
-   [ ] Make importing from region more robust
-   [ ] Prompt for correct book if uncertainty about which result is the correct book
-   [ ] org-reading-start-book should change the state to STARTED automatically
-   [ ] org-reading-finish-book should have a trigger of some kind to export books?
-   [ ] When away from the reading file append to correct heading.
-   [ ] Make it a capture event
-   [ ] Include a link to books from Amazon
## Start / Finish Book
-   [ ] Sync with Goodreads
-   [ ] When finished don't have the change of state. Just have it be marked as done.
## Find a book
-   [ ] use org-sparse-tree
-   [ ] Look for a book with a title
## Quantify Reading
-   [ ] On average how much do I read?
-   [ ] What type of books do I read?
-   [ ] Yearly graph of the type of books.
-   [ ] How long before I read something from when I add it to the list?
## Choose Next Book
-   [ ] Find a book that you might want to read.
-   [ ] Based on what you read recently come up with the next book that should be read.
## Import / Export
-   [ ] Amazon
-   [ ] Goodreads
  -   [ ] Send the review that was written to Goodreads.
  -   [ ] Pull all the books that I have in Goodreads locally
  -   [ ] Update local ratings with Goodread ratings
-   [ ] Google Books
### Goodreads

On finish trigger an update which will get the goodreads book<sub>id</sub> and
publish a review.

Have to login to Goodreads and authorize with OAuth.
1.  Get the Goodreads book ID given an ISBN
   
   Get the Goodreads book ID given an ISBN. Response contains the ID without any markup.
   URL: http://www.goodreads.com/book/isbn_to_id    (sample url)
   HTTP method: GET
   Parameters:
   key: Developer key (required).
   isbn: The ISBN of the book to lookup.
2.  Add review
   
   Add book reviews for members using OAuth. You'll need to register your app (required).
   URL: http://www.goodreads.com/review.xml
   HTTP method: POST
   Parameters:
   book<sub>id</sub>: Goodreads book<sub>id</sub> (required)
   review[review]: Text of the review (optional)
   review[rating]: Rating (0-5) (optional, default is 0 (No rating))
   review[read<sub>at</sub>]: Date (YYYY-MM-DD format, e.g. 2008-02-01) (optional)
   shelf: read|currently-reading|to-read|<USER SHELF NAME> (optional, must exist, see: shelves.list)
   
   Ability to export with an Amazon affiliate image
   
   ﻿Sync between Goodreads, Google Books, Amazon, Evernote.
   Leave an Evernote and sync it.
   
   This should belong with org-reading
